DROP TABLE IF EXISTS projects;
DROP TABLE IF EXISTS posts;
DROP TABLE IF EXISTS User;
DROP TABLE IF EXISTS threats;

CREATE TABLE threats (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL,
    created TIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    report TEXT NOT NULL
);

CREATE TABLE User (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT NOT NULL,
    password TEXT NOT NULL
);

CREATE TABLE posts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL,
    created TIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    content TEXT NOT NULL,
    
);

CREATE TABLE projects (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL,
    accountID INTEGER,
    stack TEXT NOT NULL
);